name: AnswerTheQuestion
version: 1.0.0
api:
 - 3.0.0-ALPHA12
 - 3.0.0
 - 4.0.0
author:
 - tungnguyen
 - Unickorn
description: Answer the question
main: tung\Main

commands:
  ask:
   description:
   command: /ask
   permission: ask.tung
   default: op
  t:
   description:
   command: /t
   default: true
   