#So tien member nhan dc moi khi tra loi dung
Money: 5000


#thêm câu hoi + câu tra loi tuong ung nhu ben duoi 
Questions:
  0 : "Who are you?"
  1 : "1+1=?"
  2 : "10*20=?"
  3 : "2+2="
  4 : "3+3="
  5 : "4+4="
  6 : "5+5="
Answers:
  0 : "tung"
  1 : "2"
  2 : "200"
  3 : "4"
  4 : "6"
  5 : "8"
  6 : "10"